/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as BadgesIndexRouteImport } from './routes/badges/index'
import { Route as BadgesIdRouteImport } from './routes/badges/$id'
import { Route as MetricsIndexRouteImport } from './routes/metrics/index'
import { Route as MetricsKeyRouteImport } from './routes/metrics/$key'
import { Route as MetricsNewRouteImport } from './routes/metrics/new'
import { Route as RecommendationsIndexRouteImport } from './routes/recommendations/index'
import { Route as RecommendationsIdRouteImport } from './routes/recommendations/$id'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as StoriesIdRouteImport } from './routes/stories/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesIndexRoute = BadgesIndexRouteImport.update({
  id: '/badges/',
  path: '/badges/',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesIdRoute = BadgesIdRouteImport.update({
  id: '/badges/$id',
  path: '/badges/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsIndexRoute = MetricsIndexRouteImport.update({
  id: '/metrics/',
  path: '/metrics/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsKeyRoute = MetricsKeyRouteImport.update({
  id: '/metrics/$key',
  path: '/metrics/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsNewRoute = MetricsNewRouteImport.update({
  id: '/metrics/new',
  path: '/metrics/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsIndexRoute = RecommendationsIndexRouteImport.update({
  id: '/recommendations/',
  path: '/recommendations/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsIdRoute = RecommendationsIdRouteImport.update({
  id: '/recommendations/$id',
  path: '/recommendations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIdRoute = StoriesIdRouteImport.update({
  id: '/stories/$id',
  path: '/stories/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/badges/$id': typeof BadgesIdRoute
  '/metrics/$key': typeof MetricsKeyRoute
  '/metrics/new': typeof MetricsNewRoute
  '/recommendations/$id': typeof RecommendationsIdRoute
  '/stories/$id': typeof StoriesIdRoute
  '/badges/': typeof BadgesIndexRoute
  '/metrics/': typeof MetricsIndexRoute
  '/recommendations/': typeof RecommendationsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/badges/$id': typeof BadgesIdRoute
  '/metrics/$key': typeof MetricsKeyRoute
  '/metrics/new': typeof MetricsNewRoute
  '/recommendations/$id': typeof RecommendationsIdRoute
  '/stories/$id': typeof StoriesIdRoute
  '/badges': typeof BadgesIndexRoute
  '/metrics': typeof MetricsIndexRoute
  '/recommendations': typeof RecommendationsIndexRoute
  '/stories': typeof StoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/badges/$id': typeof BadgesIdRoute
  '/metrics/$key': typeof MetricsKeyRoute
  '/metrics/new': typeof MetricsNewRoute
  '/recommendations/$id': typeof RecommendationsIdRoute
  '/stories/$id': typeof StoriesIdRoute
  '/badges/': typeof BadgesIndexRoute
  '/metrics/': typeof MetricsIndexRoute
  '/recommendations/': typeof RecommendationsIndexRoute
  '/stories/': typeof StoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preview'
    | '/badges/$id'
    | '/metrics/$key'
    | '/metrics/new'
    | '/recommendations/$id'
    | '/stories/$id'
    | '/badges/'
    | '/metrics/'
    | '/recommendations/'
    | '/stories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preview'
    | '/badges/$id'
    | '/metrics/$key'
    | '/metrics/new'
    | '/recommendations/$id'
    | '/stories/$id'
    | '/badges'
    | '/metrics'
    | '/recommendations'
    | '/stories'
  id:
    | '__root__'
    | '/'
    | '/preview'
    | '/badges/$id'
    | '/metrics/$key'
    | '/metrics/new'
    | '/recommendations/$id'
    | '/stories/$id'
    | '/badges/'
    | '/metrics/'
    | '/recommendations/'
    | '/stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewRoute: typeof PreviewRoute
  BadgesIdRoute: typeof BadgesIdRoute
  MetricsKeyRoute: typeof MetricsKeyRoute
  MetricsNewRoute: typeof MetricsNewRoute
  RecommendationsIdRoute: typeof RecommendationsIdRoute
  StoriesIdRoute: typeof StoriesIdRoute
  BadgesIndexRoute: typeof BadgesIndexRoute
  MetricsIndexRoute: typeof MetricsIndexRoute
  RecommendationsIndexRoute: typeof RecommendationsIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges/': {
      id: '/badges/'
      path: '/badges'
      fullPath: '/badges/'
      preLoaderRoute: typeof BadgesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges/$id': {
      id: '/badges/$id'
      path: '/badges/$id'
      fullPath: '/badges/$id'
      preLoaderRoute: typeof BadgesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/': {
      id: '/metrics/'
      path: '/metrics'
      fullPath: '/metrics/'
      preLoaderRoute: typeof MetricsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/$key': {
      id: '/metrics/$key'
      path: '/metrics/$key'
      fullPath: '/metrics/$key'
      preLoaderRoute: typeof MetricsKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics/new': {
      id: '/metrics/new'
      path: '/metrics/new'
      fullPath: '/metrics/new'
      preLoaderRoute: typeof MetricsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations/': {
      id: '/recommendations/'
      path: '/recommendations'
      fullPath: '/recommendations/'
      preLoaderRoute: typeof RecommendationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations/$id': {
      id: '/recommendations/$id'
      path: '/recommendations/$id'
      fullPath: '/recommendations/$id'
      preLoaderRoute: typeof RecommendationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$id': {
      id: '/stories/$id'
      path: '/stories/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof StoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewRoute: PreviewRoute,
  BadgesIdRoute: BadgesIdRoute,
  MetricsKeyRoute: MetricsKeyRoute,
  MetricsNewRoute: MetricsNewRoute,
  RecommendationsIdRoute: RecommendationsIdRoute,
  StoriesIdRoute: StoriesIdRoute,
  BadgesIndexRoute: BadgesIndexRoute,
  MetricsIndexRoute: MetricsIndexRoute,
  RecommendationsIndexRoute: RecommendationsIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
