version: "2"

linters:
  default: standard
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - wastedassign
    - whitespace

  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    nolintlint:
      require-explanation: true
      require-specific: true
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
