INSERT INTO metric_definitions (key, value_type, currency, is_public, percentile_key, comparison_min_percentile, source_key, source_field, include_in_llm, sort_order) VALUES
    ('listingsPublished', 'number', NULL, true, 'listingsPercentile', 50, 'listingsPublished', 'value', true, 10),
    ('listingsPercentile', 'percentile', NULL, true, NULL, NULL, 'listingsPublished', 'percentile', false, 11),
    ('viewsTotal', 'number', NULL, true, 'viewsPercentile', 50, 'viewsTotal', 'value', true, 20),
    ('viewsPercentile', 'percentile', NULL, true, NULL, NULL, 'viewsTotal', 'percentile', false, 21),
    ('favoritesReceived', 'number', NULL, true, 'favoritesPercentile', 50, 'favoritesReceived', 'value', true, 30),
    ('favoritesPercentile', 'percentile', NULL, true, NULL, NULL, 'favoritesReceived', 'percentile', false, 31),
    ('messagesSent', 'number', NULL, false, 'messagesPercentile', 50, 'messagesSent', 'value', true, 40),
    ('messagesPercentile', 'percentile', NULL, false, NULL, NULL, 'messagesSent', 'percentile', false, 41),
    ('dealsClosed', 'number', NULL, true, 'dealsPercentile', 50, 'dealsClosed', 'value', true, 50),
    ('dealsPercentile', 'percentile', NULL, true, NULL, NULL, 'dealsClosed', 'percentile', false, 51),
    ('moneyEarned', 'money', 'RUB', false, NULL, NULL, 'moneyEarned', 'value', true, 60),
    ('moneySaved', 'money', 'RUB', false, NULL, NULL, 'moneySaved', 'value', true, 70),
    ('daysActive', 'number', NULL, true, NULL, NULL, 'daysActive', 'value', true, 80),
    ('peakDayViews', 'number', NULL, true, NULL, NULL, 'peakDayViews', 'value', true, 90),
    ('categoriesTried', 'number', NULL, true, NULL, NULL, 'categoriesTried', 'value', true, 100),
    ('searchQueries', 'number', NULL, true, NULL, NULL, 'searchQueries', 'value', true, 110),
    ('deliveryOrders', 'number', NULL, true, NULL, NULL, 'deliveryOrders', 'value', true, 120),
    ('activeListings', 'number', NULL, false, NULL, NULL, 'activeListings', 'value', true, 130),
    ('avgReplySeconds', 'number', NULL, false, NULL, NULL, 'avgReplySeconds', 'value', false, 150),
    ('firstListingAt', 'date', NULL, false, NULL, NULL, 'firstListingAt', 'value', false, 160),
    ('firstDealAt', 'date', NULL, false, NULL, NULL, 'firstDealAt', 'value', false, 170)
ON CONFLICT (key) DO UPDATE SET
    value_type = EXCLUDED.value_type,
    currency = EXCLUDED.currency,
    is_public = EXCLUDED.is_public,
    percentile_key = EXCLUDED.percentile_key,
    comparison_min_percentile = EXCLUDED.comparison_min_percentile,
    source_key = EXCLUDED.source_key,
    source_field = EXCLUDED.source_field,
    include_in_llm = EXCLUDED.include_in_llm,
    sort_order = EXCLUDED.sort_order,
    updated_at = now();
