INSERT INTO metric_definitions (key, value_type, currency, is_public, percentile_key, sort_order) VALUES
    ('listingsPublished', 'number', NULL, true, 'listingsPercentile', 10),
    ('listingsPercentile', 'percentile', NULL, true, NULL, 11),
    ('viewsTotal', 'number', NULL, true, 'viewsPercentile', 20),
    ('viewsPercentile', 'percentile', NULL, true, NULL, 21),
    ('favoritesReceived', 'number', NULL, true, 'favoritesPercentile', 30),
    ('favoritesPercentile', 'percentile', NULL, true, NULL, 31),
    ('messagesSent', 'number', NULL, false, 'messagesPercentile', 40),
    ('messagesPercentile', 'percentile', NULL, false, NULL, 41),
    ('dealsClosed', 'number', NULL, true, 'dealsPercentile', 50),
    ('dealsPercentile', 'percentile', NULL, true, NULL, 51),
    ('moneyEarned', 'money', 'RUB', false, NULL, 60),
    ('moneySaved', 'money', 'RUB', false, NULL, 70),
    ('daysActive', 'number', NULL, true, NULL, 80),
    ('peakDayViews', 'number', NULL, true, NULL, 90),
    ('categoriesTried', 'number', NULL, true, NULL, 100),
    ('searchQueries', 'number', NULL, true, NULL, 110),
    ('deliveryOrders', 'number', NULL, true, NULL, 120),
    ('activeListings', 'number', NULL, false, NULL, 130),
    ('sellerRating', 'number', NULL, false, NULL, 140),
    ('avgReplySeconds', 'number', NULL, false, NULL, 150),
    ('firstListingAt', 'string', NULL, false, NULL, 160),
    ('firstDealAt', 'string', NULL, false, NULL, 170)
ON CONFLICT (key) DO NOTHING;
